Algoritmo "desafio02"

Var
    dia, mes, ano: inteiro
    frase, nome: caractere
Inicio
    dia <- 03
    mes <- 10
    ano <- 2024
    frase <- "Receba"
    nome <- "Antedegemon"

    escreval("*==============*****==========*")
    escreval(" Data: ", dia, "/", mes, "/", ano)
    escreval(" Mensagem do dia: ", frase)
    escreval(" Autor: ", nome)
    escreval("*==============*****==========*")
Fimalgoritmo