Algoritmo "desafio03"

Var
    nome: caractere
    idade, peso: inteiro
    altura: real
Inicio
    nome <- "Ruan"
    idade <- 21
    peso <- 84
    altura <- 1.75
    
    escreval("*============*****============*")
    escreval(" DADOS PESSOAIS")
    escreval(" Nome: ", nome)
    escreval(" Idade: ", idade, " anos")
    escreval(" Peso: ", peso, "kg")
    escreval(" Altura: ", altura, "m")
    escreval("*============*****============*")
Fimalgoritmo